homepage/urls.py
from django.urls import path, include
from homepage import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('status/', views.jawaban_status, name='jawaban_status'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8.urls')),
    path('story9/', include('story9.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

story7/urls.py
from django.urls import path, include
from story7 import views
from .views import *
from django.shortcuts import render

app_name = 'story7'

urlpatterns = [
    path('profile/', views.profile, name='profile'),
]

story8/urls.py
from django.urls import path, include
from story8 import views
from .views import *
from django.shortcuts import render

app_name = 'story8'

urlpatterns = [
    # path('books/', views.call_books, name='call_books'),
    path('list/', views.list_books, name='list_books'),
]

story9/urls.py
from django.urls import path, include
from story9 import views
from .views import *
from django.shortcuts import render

app_name = 'story9'

urlpatterns = [
    path('navigation/', views.navigations, name='navigations'),
]

homepage/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.

class HomeModel(models.Model):
    status = models.CharField(max_length=300)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms
from django.forms import ModelForm
from .models import HomeModel

class HomeForm(ModelForm):
    class Meta:
        model = HomeModel
        fields = ['status']
        labels = {'status' : 'Status :'}
        widgets = {'status' : forms.TextInput(attrs={'class' : 'form-control', 'type' : 'text'})}

homepage/views.py
from django.shortcuts import render, redirect, reverse
from .forms import HomeForm
from .models import HomeModel
from django.contrib import messages
from django.http import HttpResponseRedirect

# Create your views here.

def home(request): 
    form = HomeForm()
    database = HomeModel.objects.all()
    content = {'form':form, 'database':database}
    return render(request, 'home.html', content)

def jawaban_status(request):
    if request.method == 'POST':
        form = HomeForm(request.POST)
        if form.is_valid():
            fields = ['status', 'created_at']
            form.save()

    return redirect(reverse('homepage:home'))

story7/views.py
from django.shortcuts import render, redirect

# Create your views here.
def profile(request):
    return render(request, 'profile.html')

story8/views.py
from django.shortcuts import render
from django.shortcuts import redirect
import requests
import json
from django.http import JsonResponse

# Create your views here.
# def call_books(request, keyword):
#     r = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + keyword)
#     return JsonResponse(r.json())

def list_books(request):
    return render(request, 'books.html')

story9/views.py
from django.shortcuts import render
from django.shortcuts import redirect

# Create your views here.

def navigations(request):
    return render(request, 'navigation.html')

homepage/templates/base.html
<!-- <!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Cantarell|Chelsea+Market|Bad+Script|Knewave&display=swap" rel="stylesheet">
    
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
        <title>Home</title>
    </head>

    {% block content %}
    {% endblock content %}

</html> -->

homepage/templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- BootstrapCDN CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Cantarell|Chelsea+Market|Bad+Script|Knewave&display=swap" rel="stylesheet">
    
   
        <!-- BootstrapCDN JavaScript -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        
        <title>Home</title>
    </head>
    <body>
        <div class="container py-5">
            <div class="row">
                <div class="judul_dan_form_status">
                    <div id="judul_halo">
                        <br>
                        <h1>Halo, apa kabar?</h1>
                    </div>
                    <br>
                    <div id="form_status">
                        <form action="{% url 'homepage:jawaban_status' %}" method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}                
                            <span>
                                <input type="submit" value="Simpan Status" class="btn btn-primary">
                            </span>
                        </form>
                    </div>
                </div>
                <br>
                <br>
                <div class="table-responsive">
                    <div class="tabel_list_status">
                        <table class="table table-fixed" border-collapse="collapse" width="100%">
                            <thead>
                                <tr>
                                    <th class="text-center" style="width: 50%" scope="col" padding="8px 16px">Status</th>
                                    <th class="text-center" style="width: 50%" scope="col" padding="8px 16px">Waktu</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for all in database %}
                                    <tr>
                                        <td class="text-center" style="width: 50%" scope="col">{{ all.status }}</td>
                                        <td class="text-center" style="width: 50%" scope="col">{{ all.created_at }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>     
   </body>
</html>

story7/templates/profile.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- BootstrapCDN CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Cantarell|Chelsea+Market|Bad+Script|Knewave&display=swap" rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'style_story7.css' %}">
   
        <!-- BootstrapCDN JavaScript -->
        <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="{% static 'script.js' %}"></script>

        <title>Profile</title>
    </head>

    <body>
        <div class="col-md-12">
            <div class="container">
                <div class="col-md-auto">
                    <!-- ini buat gambar kucing -->
                </div>
            </div>

            <div class="row justify-content-md-center">
              <div class="col-md-auto">
                    <button type="button" id="ganti-tema" class="btn btn-light">ngantuuuk</button>
              </div>
            </div><br>

           <div class="row justify-content-md-center">
                <div class="col-md-auto">
                    <h1>Informasi Tentang Saya</h1>
                </div>
            </div><br>

            <center>
                <div>
                <!-- accordion -->
                    <div class="accordion">

                        <div class="accordion-header">
                            Aktivitas
                        </div>
                        <div class="accordion-content">
                            Makan <br>
                            Kuliah <br>
                            Nugas <br>
                            Tidur
                        </div>

                        <div class="accordion-header">
                            Pengalaman Organisasi/Kepanitiaan
                        </div>
                        <div class="accordion-content">
                            BEM Fasilkom UI 2019 <br>
                            FUKI Fasilkom UI 2019 <br>
                            SIWAK-NG 2019 <br>
                        </div>

                        <div class="accordion-header">
                            Prestasi
                        </div>
                        <div class="accordion-content">
                            Belum ada prestasi T_T
                        </div>

                    </div> 
                <!-- accordion -->
                </div>
            </center>
        </div>
    </body>
</html>

story8/templates/books.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- BootstrapCDN CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Cantarell|Chelsea+Market|Bad+Script|Knewave&display=swap" rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'style_story8.css' %}">
   
        <!-- BootstrapCDN JavaScript -->
        <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        

        <title>Books</title>
    </head>

    <body>
        <center>
            <div class="mb-5 mx-5 py-2 flex-center-col align-c">
                <br>
                <h1>Sedang cari buku apa?</h1>
                <br>
                <form class="justify-content-md-center">
                    <div class="input-group mb-3">
                        <input id="input-search" type="text" class="form-control" placeholder="Masukkan judul buku" aria-label="Masukkan judul buku" aria-describedby="button-addon2">
                        <div class="input-group-append">
                            <button id="button-search" class="btn btn-outline-secondary" type="button" id="button-addon2">Cari Buku</button>
                        </div>
                     </div>
                </form>
            </div>
            <h3>Berikut ini buku hasil pencarianmu :</h3>
            <br>
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="text-center" style="width: 20%" scope="col">Judul</th>
                    <th class="text-center" style="width: 20%" scope="col">Penulis</th>
                    <th class="text-center" style="width: 20%" scope="col">Penerbit</th>
                    <th class="text-center" style="width: 20%" scope="col">Kategori</th>
                    <th class="text-center" style="width: 20%" scope="col"></th>
                  </tr>
                </thead>

                <tbody id="results">

                </tbody>
              </table>

        </center>
    </body>
    <script src="{% static 'script_story8.js' %}"></script>
</html>

story9/templates/navigation.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <!-- BootstrapCDN CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Cantarell|Chelsea+Market|Bad+Script|Knewave&display=swap" rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'style_story9.css' %}">
   
        <!-- BootstrapCDN JavaScript -->
        <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        

        <title>Navigation</title>
    </head>

    <body class="nav_body">
        {% if form.errors %}
      <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
      {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
      {% else %}
        <p>Please login to see this page.</p>
      {% endif %}
    {% endif %}
       <div class="container">
            <div id="tulisan">
                <div class="row justify-content-md-center">
                    <div class="col-md-auto welcome">
                        <h3>Selamat datang,</h3>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <div class="col-md-auto name">
                        <h1>{{ user.get_username }}!</h1>
                    </div>
                </div>
                <div class="row justify-content-md-center">
                    <div class="col-md-auto">
                        <h3>Silakan kunjungi halaman di bawah ini</h3>
                    </div>
                </div>
            </div>
            
            <div class="row" id="buttons">
                <div class="col-sm text-center">
                    <a href="{% url 'homepage:home' %}" class="btn btn-outline-danger">Homepage</a>
                </div>
                <div class="col-sm text-center">
                    <a href="{% url 'story7:profile' %}" class="btn btn-outline-danger">Profile</a>
                </div>
                <div class="col-sm text-center">
                    <a href="{% url 'story8:list_books' %}" class="btn btn-outline-danger">Books</a>
                </div>
            </div>

            <div class="row justify-content-md-center logout">
                <div class="col-md-auto">
                    <h3>atau keluar</h3>
                </div>
            </div>

            <div class="row justify-content-md-center logout-button">
                <a href="{% url 'logout'%}" class="btn btn-danger btn-lg">Logout</a>
            </div>
        </div>
    </body>
    
</html>